#
# Table structure for table `mos_zoom`
#

DROP TABLE IF EXISTS mos_zoom;
CREATE TABLE mos_zoom (
  id int(3) unsigned NOT NULL auto_increment,
  catname varchar(25) default '0',
  catdescr varchar(180) default NULL,
  catdir varchar(25) default '0',
  catimg int(3) default NULL,
  PRIMARY KEY  (id),
  KEY id (id)
);
# --------------------------------------------------------
#
# Table structure for table `mos_zoom_comments`
#

DROP TABLE IF EXISTS mos_zoom_comments;
CREATE TABLE mos_zoom_comments (
  id int(11) NOT NULL auto_increment,
  image_id int(11) NOT NULL default '0',
  name varchar(40) NOT NULL default '',
  comment varchar(180) NOT NULL default '',
  date timestamp(14) NOT NULL,
  PRIMARY KEY  (id),
  KEY ID (id)
);
# --------------------------------------------------------
#
# Table structure for table `mos_zoomfiles`
#

DROP TABLE IF EXISTS mos_zoomfiles;
CREATE TABLE mos_zoomfiles (
  id int(3) unsigned NOT NULL auto_increment,
  name varchar(30) NOT NULL default '',
  descr varchar(180) default NULL,
  hits bigint(20) NOT NULL default '0',
  gallery_id int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (id),
  KEY id (id)
);
# --------------------------------------------------------
#
# Table structure for table `mos_zoom_config`
#
DROP TABLE IF EXISTS mos_zoom_config;
CREATE TABLE mos_zoom_config (
  conversiontype tinyint(1) NOT NULL default '1',
  imagepath varchar(60) NOT NULL default 'images/zoom/',
  IM_path varchar(60) NOT NULL default 'd:/ImageMagick/',
  NETPBM_path varchar(60) NOT NULL default 'c:/NETPBM/',
  size smallint(3) NOT NULL default '100',
  JPEGquality smallint(3) NOT NULL default '85',
  columnsno smallint(2) NOT NULL default '3',
  PageSize smallint(6) NOT NULL default '6',
  tempDescr varchar(240) NOT NULL default 'Temporary description, please change...',
  commentsOn tinyint(1) NOT NULL default '1',
  popUpImages tinyint(1) NOT NULL default '0',
  catImg tinyint(1) NOT NULL default '1',
  slideshow tinyint(1) NOT NULL default '1',
  readEXIF tinyint(1) NOT NULL default '0',
  displaylogo tinyint(1) NOT NULL default '1',
  allowUserUpload tinyint(1) NOT NULL default '1',
  version varchar(12) NOT NULL default '2.0',
  PRIMARY KEY  (conversiontype)
);
# --------------------------------------------------------
#
# populate table `mos_zoom_config`
#
INSERT INTO mos_zoom_config VALUES (1, 'images/zoom/', 'd:/ImageMagick/', 'c:/NETPBM/', 100, 85, 3, 6, 'Temporary description, please change...', 1, 0, 1, 1, 0, 0, 1, '2.0');
# sql-statements generated by phpMyAdmin 2.4.0
